### ISSUE TITLE
How to provide Lanes as const parameter?

### ISSUE THREAD

**Issue by Rikorose** [rust-lang/stdsimd#88]
I have a function that works on chunks of data. The chunks have a fixed size that I specify via const generics. The chunk size should be used as Lanes parameter for `SimdF32::from_array`; however, I fail to pass a const parameter to the from_array function.

```rust
use core_simd::{SimdF32, LanesAtMost64};

// Some function that needs a const parameter which also corresponds to SimdF32 LANES
pub fn from_array<const N: usize>(x: [f32; N]) -> SimdF32<N> {
    // How can I pass N to from_array?
    SimdF32::<N>::from_array(x)
}

#[test]
fn simd_array() {
    const LANES: usize = 8;
    let x = [0.; LANES];
    let x_simd = from_array::<LANES>(x);
    for (x_, y_) in x.iter().zip(x_simd.to_array()) {
        assert_eq!(x_, y_);
    }
}
```
Result (without warnings):
```
$ cargo +nightly test
   Compiling benches v0.0.1 (/home/hendrik/projects/rs_benches)

error[E0277]: the trait bound `SimdF32<N>: LanesAtMost64` is not satisfied
  --> src/test_simd.rs:4:51
   |
4  | pub fn from_array<const N: usize>(x: [f32; N]) -> SimdF32<N>
   |                                                   ^^^^^^^^^^ the trait `LanesAtMost64` is not implemented for `SimdF32<N>`
   |
  ::: /home/hendrik/.cargo/git/checkouts/stdsimd-26e23068d55c82a1/4e6d440/crates/core_simd/src/vector/float.rs:47:11
   |
47 |     Self: crate::LanesAtMost64;
   |           -------------------- required by this bound in `SimdF32`
   |
   = help: the following implementations were found:
             <SimdF32<16_usize> as LanesAtMost64>
             <SimdF32<1_usize> as LanesAtMost64>
             <SimdF32<2_usize> as LanesAtMost64>
             <SimdF32<32_usize> as LanesAtMost64>
           and 3 others

error[E0277]: the trait bound `SimdF32<N>: LanesAtMost64` is not satisfied
  --> src/test_simd.rs:4:51
   |
4  | pub fn from_array<const N: usize>(x: [f32; N]) -> SimdF32<N>
   |                                                   ^^^^^^^^^^ the trait `LanesAtMost64` is not implemented for `SimdF32<N>`
   |
  ::: /home/hendrik/.cargo/git/checkouts/stdsimd-26e23068d55c82a1/4e6d440/crates/core_simd/src/vector/float.rs:47:11
   |
47 |     Self: crate::LanesAtMost64;
   |           -------------------- required by this bound in `SimdF32`
   |
   = help: the following implementations were found:
             <SimdF32<16_usize> as LanesAtMost64>
             <SimdF32<1_usize> as LanesAtMost64>
             <SimdF32<2_usize> as LanesAtMost64>
             <SimdF32<32_usize> as LanesAtMost64>
           and 3 others

error: aborting due to previous error; 3 warnings emitted

For more information about this error, try `rustc --explain E0277`.
error: aborting due to previous error; 3 warnings emitted

For more information about this error, try `rustc --explain E0277`.
error: could not compile `benches`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

And with the trait:
```rust
use core_simd::{SimdF32, LanesAtMost64};

// Some function that needs a const parameter which also corresponds to SimdF32 LANES
pub fn from_array<const N: usize>(x: [f32; N]) -> SimdF32<N> 
    where SimdF32<N>: LanesAtMost64
{
    SimdF32::<N>::from_array(x)
}

#[test]
fn simd_array() {
    const LANES: usize = 8;
    let x = [0.; LANES];
    let x_simd = from_array::<LANES>(x);
    for (x_, y_) in x.iter().zip(x_simd.to_array()) {
        assert_eq!(x_, y_);
    }
}
```
Results in an internal compiler error:
```
$ cargo +nightly test
   Compiling benches v0.0.1 (/home/hendrik/projects/rs_benches)
error: internal compiler error: compiler/rustc_middle/src/ich/impls_ty.rs:94:17: StableHasher: unexpected region '_#0r

thread 'rustc' panicked at 'Box<Any>', /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (c755ee4ce 2021-04-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `vec::<impl at src/vec.rs:32:1: 58:2>::new`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: internal compiler error: compiler/rustc_middle/src/ich/impls_ty.rs:94:17: StableHasher: unexpected region '_#0r

thread 'rustc' panicked at 'Box<Any>', /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (c755ee4ce 2021-04-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `vec::<impl at src/vec.rs:32:1: 58:2>::new`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to previous error; 2 warnings emitted

error: aborting due to previous error; 2 warnings emitted

error: could not compile `benches`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Lokathor** [comment]
What the error is (badly) trying to say is that you can't have `from_array` be generic over any usize, because you can't make a SimdF32 for any lane count. The LanesAtMost64 needs to also be placed on your own function as well. It doesn't matter that you only use it for size 8, you need the bound because rust favors explicit boilerplate over post-monomorphization errors.

**Comment by Rikorose** [comment]
Thanks for your answer. How can I specify the LanesAtMost64 trait for the function? I tried this in the second example, but got the internal compiler error.

**Comment by Lokathor** [comment]
I've never had to do it this way before myself, but based on this line https://github.com/rust-lang/stdsimd/blob/master/crates/core_simd/src/math.rs#L3

i think you can put a where clause after the return value, something like
```
where SimdF32<N>: LanesAtMost64 {
```

**Comment by Rikorose** [comment]
Yes this is what I tried in the second example in the original post. This resulted in the compiler error.

**Comment by Lokathor** [comment]
Ah, there's a 2nd example in there that i missed, right.

@calebzulawski may know?

**Comment by workingjubilee** [comment]
@Rikorose Hello, I cannot reproduce this apparently? I generate some compiler errors, but otherwise, copying your second function and with the modification:
`&x_simd.to_array()`
in the test, my version compiles **and** passes.

```
> rustc --version --verbose
rustc 1.53.0-nightly (d32238532 2021-04-05)
binary: rustc
commit-hash: d32238532138485c80db4f2cd596372bce214e00
commit-date: 2021-04-05
host: x86_64-pc-windows-msvc
release: 1.53.0-nightly
LLVM version: 12.0.0
```

**Comment by calebzulawski** [comment]
This may be a bug in const generics on some particular version of nightly that's now fixed?

**Comment by Rikorose** [comment]
Indeed, I guess it was a bug in the nightly version that I used. Works now, thanks!
